version: "3.9"
services:
  spring-ticket-generator:
    image: onuraltuntasb/spring-ticket-generator:latest
    ports:
      - "8080:8080"
    networks:
      - mysql-network
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    networks:
      - mysql-network
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket_generator
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+00:00']
    expose:
      - "3333"
    ports:
      - "3333:3306"

networks:
  mysql-network:
