version: "3.9"
services:
  spring-ticket-generator:
    image: onuraltuntasb/spring-ticket-generator
    ports:
      - "8080:8080"
    networks:
      - ticket-generator-mysql-network
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3307/ticket_generator?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql
    networks:
      - ticket-generator-mysql-network
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket_generator
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+00:00']
    expose:
      - "3306"
    ports:
      - "3306:3306"

networks:
  ticket-generator-mysql-network:
