version: "3.9"
services:

  mysqldb:
    image: mysql:8.0
    networks:
      - mysql-network
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket_generator
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+00:00']
    expose:
      - "3306"
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  spring-ticket-generator:
    image: onuraltuntasb/spring-ticket-generator
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - mysql-network
    depends_on:
      mysqldb:
        condition: service_healthy

networks:
  mysql-network:
