version: "3.9"
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_ticket_generator
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+00:00']
    expose:
      - "3307"
    ports:
      - "3307:3306"