
#TODO application env variables injection is broken!!!
jwtSecret:
  secretKey
jwtExpirationMs:
  86400000 # 1day
jwtRefreshExpirationSecond:
  25920000 # 1month

#url

spring:
  datasource:
    url: jdbc:mysql://mysqldb:3333/ticket_generator?createDatabaseIfNotExist=true&autoReconnect=false&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: onur
    password: onur_pw
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 1000
        #generate_statistics: true

server:
  port: 8080


logging:
  level:
    org:
      springframework:
        jdbc:
          core=TRACE:

