
#TODO secret key change for production
jwtSecret:
  secretKey
jwtExpirationMs:
  86400000 # 1day
jwtRefreshExpirationSecond:
  25920000 # 1month

#url

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/spring_ticket_generator
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
server:
  port: 8081

