
#TODO application env variables injection is broken!!!
jwtSecret:
  secretKey
jwtExpirationMs:
  86400000 # 1day
jwtRefreshExpirationSecond:
  25920000 # 1month

#url

spring:
  datasource:
    url: jdbc:mysql://ticket-generator-mysql:3307/mysqldb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 1000
        #generate_statistics: true

server:
  port: 8081


logging:
  level:
    org:
      springframework:
        jdbc:
          core=TRACE:

