spring:
  datasource:
    url: jdbc:mysql://localhost:3333/ticket_generator?createDatabaseIfNotExist=true&serverTimezone=UTC&autoReconnect=false&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 1000
        #generate_statistics: true
  sql:
    init:
      mode: always
      platform: mysql
  devtools:
    livereload:
      enabled: true

server:
  port: 8080


logging:
  level:
    org:
      springframework:
        jdbc:
          core=TRACE:




